
baseURL = "https://megamind111.github.io/gifts1500-site/"
languageCode = "en-us"
title = "Gifts Under ₹1,500"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Your Name"
  defaultTheme = "light"
  ShowReadingTime = true
